// Generated by CoffeeScript 1.9.1
(function() {
  var helpers;

  helpers = require('helpers');

  exports.moneyIn = function(money) {
    return Math.floor(Number(money) * 1e8);
  };

  exports.moneyOut = function(satoshi) {
    var bitcoin_string, decimal_place;
    satoshi = helpers.pad(satoshi, 9, '0');
    decimal_place = satoshi.length - 8;
    bitcoin_string = satoshi.slice(0, decimal_place).concat('.').concat(satoshi.slice(decimal_place, satoshi.length));
    return helpers.antipad(bitcoin_string, '0');
  };

}).call(this);
