// Generated by CoffeeScript 1.4.0
(function() {

  exports.moneyIn = function(money) {
    return Math.floor(money * 1e8);
  };

  exports.moneyOut = function(money) {
    return Math.floor(money / 1e4) / 1e4;
  };

}).call(this);
